# Copyright (c) 2022 MobileCoin Inc.
name: ci

on:
  pull_request:
  push:
    tags:
    - v*.*.*

env:
  PUSH_LATEST: ${{ github.event_name == 'pull_request' && 'false' || 'true' }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  lint-actions:
    runs-on: mco-dev-small-x64
    steps:
    - name: Lint GitHub Actions
      uses: mobilecoinofficial/gh-actions/lint-actions@v0

  lint-docker:
    runs-on: mco-dev-small-x64
    steps:
    - name: Lint Dockerfiles with Hadolint
      uses: mobilecoinofficial/gh-actions/lint-docker@v0

  docker-rust-base:
    needs:
    - lint-actions
    - lint-docker
    strategy:
      matrix:
        runner:
        - mco-dev-small-x64
        - mco-dev-small-arm64
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Checkout
      uses: mobilecoinofficial/gh-actions/checkout@v0

    - name: Docker rust-base
      id: build
      uses: mobilecoinofficial/gh-actions/docker@v0
      with:
        dockerfile: Dockerfile.rust-base
        images: mobilecoin/rust-base
        outputs: type=image,name=mobilecoin/rust-base,push-by-digest=true,name-canonical=true,push=true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        save_digest: true

  docker-rust-base-merge:
    runs-on: mco-dev-small-x64
    needs:
    - docker-rust-base
    steps:
    - name: Merge and Tag Digests
      uses: mobilecoinofficial/gh-actions/docker-merge-digests@v0
      with:
        images: mobilecoin/rust-base
        flavor: latest=${{ env.PUSH_LATEST }}
        tags: |
          type=semver,pattern=v{{version}}
          type=sha
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-rust-sgx:
    needs:
    - docker-rust-base-merge
    runs-on: mco-dev-small-x64
    steps:
    - name: Checkout
      uses: mobilecoinofficial/gh-actions/checkout@v0

    - name: Short Sha
      id: short_sha
      uses: mobilecoinofficial/gh-actions/short-sha@v0

    - name: Docker rust-sgx
      uses: mobilecoinofficial/gh-actions/docker@v0
      with:
        dockerfile: Dockerfile.rust-sgx
        flavor: latest=${{ env.PUSH_LATEST }}
        images: mobilecoin/rust-sgx
        tags: |
          type=semver,pattern=v{{version}}
          type=sha
        build_args: |
          BASE_IMAGE_TAG=${{ steps.short_sha.outputs.short_sha }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-fat-sgx-builder:
    needs:
    - docker-rust-sgx
    runs-on: mco-dev-small-x64
    steps:
    - name: Checkout
      uses: mobilecoinofficial/gh-actions/checkout@v0

    - name: Short Sha
      id: short_sha
      uses: mobilecoinofficial/gh-actions/short-sha@v0

    - name: Docker fat-sgx-builder
      uses: mobilecoinofficial/gh-actions/docker@v0
      with:
        dockerfile: Dockerfile.fat-builder
        flavor: latest=${{ env.PUSH_LATEST }}
        images: mobilecoin/fat-sgx-builder
        build_args: |
          BASE_IMAGE=rust-sgx
          BASE_IMAGE_TAG=${{ steps.short_sha.outputs.short_sha }}
        tags: |
          type=semver,pattern=v{{version}}
          type=sha
        push: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-fat-sgx-devcontainer:
    needs:
    - docker-fat-sgx-builder
    runs-on: mco-dev-small-x64
    steps:
    - name: Checkout
      uses: mobilecoinofficial/gh-actions/checkout@v0

    - name: Short Sha
      id: short_sha
      uses: mobilecoinofficial/gh-actions/short-sha@v0

    - name: Docker fat-sgx-devcontainer
      uses: mobilecoinofficial/gh-actions/docker@v0
      with:
        dockerfile: Dockerfile.devcontainer
        flavor: latest=${{ env.PUSH_LATEST }}
        images: mobilecoin/fat-sgx-devcontainer
        build_args: |
          BASE_IMAGE=fat-sgx-builder
          BASE_IMAGE_TAG=${{ steps.short_sha.outputs.short_sha }}
        tags: |
          type=semver,pattern=v{{version}}
          type=sha
        push: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-fat-builder:
    needs:
    - docker-rust-base-merge
    strategy:
      matrix:
        runner:
        - mco-dev-small-x64
        - mco-dev-small-arm64
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Checkout
      uses: mobilecoinofficial/gh-actions/checkout@v0

    - name: Short Sha
      id: short_sha
      uses: mobilecoinofficial/gh-actions/short-sha@v0

    - name: Docker fat-builder
      id: build
      uses: mobilecoinofficial/gh-actions/docker@v0
      with:
        dockerfile: Dockerfile.fat-builder
        images: mobilecoin/fat-builder
        build_args: |
          BASE_IMAGE=rust-base
          BASE_IMAGE_TAG=${{ steps.short_sha.outputs.short_sha }}
        outputs: type=image,name=mobilecoin/fat-builder,push-by-digest=true,name-canonical=true,push=true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        save_digest: true

  docker-fat-builder-merge:
    runs-on: mco-dev-small-x64
    needs:
    - docker-fat-builder
    steps:
    - name: Merge and Tag Digests
      uses: mobilecoinofficial/gh-actions/docker-merge-digests@v0
      with:
        images: mobilecoin/fat-builder
        flavor: latest=${{ env.PUSH_LATEST }}
        tags: |
          type=semver,pattern=v{{version}}
          type=sha
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

  docker-fat-devcontainer:
    needs:
    - docker-fat-builder-merge
    strategy:
      matrix:
        runner:
        - mco-dev-small-x64
        - mco-dev-small-arm64
    runs-on: ${{ matrix.runner }}
    steps:
    - name: Checkout
      uses: mobilecoinofficial/gh-actions/checkout@v0

    - name: Short Sha
      id: short_sha
      uses: mobilecoinofficial/gh-actions/short-sha@v0

    - name: Docker fat-builder
      id: build
      uses: mobilecoinofficial/gh-actions/docker@v0
      with:
        dockerfile: Dockerfile.devcontainer
        images: mobilecoin/fat-devcontainer
        build_args: |
          BASE_IMAGE=fat-builder
          BASE_IMAGE_TAG=${{ steps.short_sha.outputs.short_sha }}
        outputs: type=image,name=mobilecoin/fat-devcontainer,push-by-digest=true,name-canonical=true,push=true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        save_digest: true

  docker-fat-devcontainer-merge:
    runs-on: mco-dev-small-x64
    needs:
    - docker-fat-devcontainer
    steps:
    - name: Merge and Tag Digests
      uses: mobilecoinofficial/gh-actions/docker-merge-digests@v0
      with:
        images: mobilecoin/fat-devcontainer
        flavor: latest=${{ env.PUSH_LATEST }}
        tags: |
          type=semver,pattern=v{{version}}
          type=sha
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

  success:
    needs:
    - docker-fat-devcontainer-merge
    - docker-fat-sgx-devcontainer
    runs-on: mco-dev-small-x64
    steps:
    - name: Success
      run: echo "All Builds Success"
