# Copyright (c) 2022 MobileCoin Inc.
name: ci

env:
  DOCKER_REPO: mobilecoin/rust-sgx-base

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  docker:
    runs-on: [self-hosted, Linux, small]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        flavor: |
          latest=true
        images: ${{ env.DOCKER_REPO }}
        tags: |
          type=ref,event=branch
          type=semver,pattern=v{{version}}
          type=semver,pattern=v{{major}}.{{minor}}
          type=semver,pattern=v{{major}}
          type=sha

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push rust-sgx-base
      uses: docker/build-push-action@v3
      with:
        target: rust-sgx-base
        cache-from: type=registry,ref=${{ env.DOCKER_REPO }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_REPO }}:buildcache
        context: .
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}

    - name: Build and push builder-install
      uses: docker/build-push-action@v3
      with:
        target: builder-install
        cache-from: type=registry,ref=${{ env.DOCKER_REPO }}:buildcache
        cache-to: type=registry,ref=${{ env.DOCKER_REPO }}:buildcache
        context: .
        labels: ${{ steps.meta.outputs.labels }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
