# Copyright (c) 2022 MobileCoin Inc.
name: tag

on:
  push:
    branches:
    - main

jobs:
  tag:
    runs-on: mco-dev-small-x64
    steps:
    # We need to use an external PAT here because GHA will not run downstream events if we use the built in token.
    - name: bump tag
      uses: mobilecoinofficial/gh-actions/tag@v0
      with:
        github_token: ${{ secrets.ACTIONS_TOKEN }}
